# Site settings
title: Amaresh Sahu
email: amaresh.sahu@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Amaresh Sahu's personal website. Currently a chemical engineering PhD
  Candidate at UC Berkeley, using irreversible thermodynamics, statistical
  mechanics, and continuum mechanics to model the biological cell membrane.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amaresh-sahu.github.io/" # the base hostname & protocol for your site
# twitter_username: amaresh_sahu_
# github_username:  amaresh-sahu
# linkedin_username: amaresh-sahu-0735ab96
# linkedin_link: amaresh-sahu

# Build settings
markdown: kramdown
