# Site settings
title: Amaresh Sahu
email: amaresh.sahu@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Amaresh Sahu's personal website. Currently a postdoc at Weill Cornell
  Medicine, developing theories of neurons and the nervous system.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amaresh-sahu.github.io/" # the base hostname & protocol for your site
# twitter_username: amaresh_sahu_
# github_username:  amaresh-sahu
# linkedin_username: amaresh-sahu-0735ab96
# linkedin_link: amaresh-sahu

# Build settings
markdown: kramdown
