# Site settings
title: Amaresh Sahu
email: amaresh.sahu07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amaresh-sahu.github.io" # the base hostname & protocol for your site
twitter_username: paparesh
github_username:  amaresh-sahu

# Build settings
markdown: kramdown
highlighter: pygments
